### PR TITLE
Fix incompatibility to new API v2

### LINKED ISSUE #36: Use API v2
[Draculente/mensa-api](https://github.com/Draculente/mensa-api) was recently ported to Rust, with a different API than before.

The old API will be deactivated soon!

### PR DESCRIPTION
**Pull request by hoppjan**
fixes #36

### CODE REVIEW

**Comment by hoppjan** [comment]
Be aware: this might require a fresh installation, since I had to change some of the model classes

File: app/src/main/kotlin/de/janhopp/luebeckmensawidget/api/MensaApi.kt [hunk 1]
```diff
@@ -16,9 +18,10 @@ class MensaApi(
         get() = currentTime.mensaApiFormat
 
     suspend fun getMealsToday(): List<MensaDay> = runCatching {
-        client.get("https://speiseplan.mcloud.digital/meals?date=$date")
+        client.get("https://speiseplan.mcloud.digital/v2/meals?location=ME&date=$date")
```
Comment (Draculente) [inline app/src/main/kotlin/de/janhopp/luebeckmensawidget/api/MensaApi.kt:21]: It probably should be "location=ME,CA", because the Mensa and Cafeteria are treated as different locations.

Comment (hoppjan) [reply app/src/main/kotlin/de/janhopp/luebeckmensawidget/api/MensaApi.kt:21]: The widget filtered this before as well and only ever showed Mensa meals

Comment (Draculente) [reply app/src/main/kotlin/de/janhopp/luebeckmensawidget/api/MensaApi.kt:21]: Ohhh

**Comment by Importantus** [comment]
Nice work! 🥳 But I would wait a little with merging because there is an [open issue](https://github.com/Draculente/mensa-api/issues/12) for the api to change the location codes.

**Comment by hoppjan** [comment]
The change works, @Draculente 🎉
